from langchain_core.documents import Document


def rrf(v_result,b_result):
    scores = {}
    docs = {}
    for index,score in enumerate(v_result,start=1):
        scores[score.id] = scores.get(score.id,0)+round(1/(60+index),4)
        docs[score.id] = score
    for index,doc in enumerate(b_result,start=1):
        scores[doc.id] = scores.get(doc.id,0)+round(1/(60+index),4)
        docs[doc.id] = doc
    sorted_scores = sorted(scores.items(),key=lambda x:x[1],reverse=True)
    # print(sorted_scores)
    result = [docs[id] for id,score in sorted_scores]
    # print(result)
    return result


if __name__ == '__main__':
    v_result = [Document(id='86ad1e8c-a4a0-4146-aebb-09f731eafede', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第三十三条规定，加害人实施家庭暴力，构成违反治安管理行为的，依法给予治安管理处罚；构成犯罪的，依法追究刑事责任。'), Document(id='f57d0b95-cdde-4bc4-b63d-59e13818e963', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第三十七条规定，家庭成员以外共同生活的人之间实施的暴力行为，参照本法规定执行。'), Document(id='1dd405d8-49d6-48a0-a7a5-e864cfd40e44', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第二十六条规定，人身安全保护令由人民法院以裁定形式作出。'), Document(id='2e380b39-e291-4f71-8d8b-ad0b8dd07cbe', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第十六条规定，家庭暴力情节较轻，依法不给予治安管理处罚的，由公安机关对加害人给予批评教育或者出具告诫书。告诫书应当包括加害人的身份信息、家庭暴力的事实陈述、禁止加害人实施家庭暴力等内容。'), Document(id='6fd121cd-df66-4abf-96e3-a074b8e04b9f', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第三十六条规定，负有反家庭暴力职责的国家工作人员玩忽职守、滥用职权、徇私舞弊的，依法给予处分；构成犯罪的，依法追究刑事责任。'), Document(id='a7d3dcf1-40e8-4f67-9ce5-4dabb509a15a', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第二十七条规定，作出人身安全保护令，应当具备下列条件：（一）有明确的被申请人；（二）有具体的请求；（三）有遭受家庭暴力或者面临家庭暴力现实危险的情形。'), Document(id='c0c389fc-ae53-4f14-b5a9-0618d7e8993b', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第二十五条规定，人身安全保护令案件由申请人或者被申请人居住地、家庭暴力发生地的基层人民法院管辖。'), Document(id='f97e45b8-0f50-4bd8-9ec1-37cc2fc885f2', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第二十九条规定，人身安全保护令可以包括下列措施：（一）禁止被申请人实施家庭暴力；（二）禁止被申请人骚扰、跟踪、接触申请人及其相关近亲属；（三）责令被申请人迁出申请人住所；（四）保护申请人人身安全的其他措施。'), Document(id='5723459d-6178-4ae0-8ef3-3942695f9f4a', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第二十条规定，人民法院审理涉及家庭暴力的案件，可以根据公安机关出警记录、告诫书、伤情鉴定意见等证据，认定家庭暴力事实。'), Document(id='4e827d6a-79cc-4d29-81e5-22ef322a51c8', metadata={'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}, page_content='《中华人民共和国反家庭暴力法》第十条规定，人民调解组织应当依法调解家庭纠纷，预防和减少家庭暴力的发生。')]
    b_result = [Document(id='2e380b39-e291-4f71-8d8b-ad0b8dd07cbe', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第十六条规定，家庭暴力情节较轻，依法不给予治安管理处罚的，由公安机关对加害人给予批评教育或者出具告诫书。告诫书应当包括加害人的身份信息、家庭暴力的事实陈述、禁止加害人实施家庭暴力等内容。'), Document(id='e8e69229-db1e-47df-91bf-aa6270245d8a', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第十五条规定，公安机关接到家庭暴力报案后应当及时出警，制止家庭暴力，按照有关规定调查取证，协助受害人就医、鉴定伤情。无民事行为能力人、限制民事行为能力人因家庭暴力身体受到严重伤害、面临人身安全威胁或者处于无人照料等危险状态的，公安机关应当通知并协助民政部门将其安置到临时庇护场所、救助管理机构或者福利机构。'), Document(id='4e827d6a-79cc-4d29-81e5-22ef322a51c8', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第十条规定，人民调解组织应当依法调解家庭纠纷，预防和减少家庭暴力的发生。'), Document(id='6fd121cd-df66-4abf-96e3-a074b8e04b9f', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第三十六条规定，负有反家庭暴力职责的国家工作人员玩忽职守、滥用职权、徇私舞弊的，依法给予处分；构成犯罪的，依法追究刑事责任。'), Document(id='c0c389fc-ae53-4f14-b5a9-0618d7e8993b', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第二十五条规定，人身安全保护令案件由申请人或者被申请人居住地、家庭暴力发生地的基层人民法院管辖。'), Document(id='2c062048-0d87-46ff-9df6-d55baf6d43f5', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第十九条规定，法律援助机构应当依法为家庭暴力受害人提供法律援助。人民法院应当依法对家庭暴力受害人缓收、减收或者免收诉讼费用。'), Document(id='d59bbbd8-9f9e-45a1-ab3f-fbe12794bcb0', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第十二条规定，未成年人的监护人应当以文明的方式进行家庭教育，依法履行监护和教育职责，不得实施家庭暴力。'), Document(id='86ad1e8c-a4a0-4146-aebb-09f731eafede', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第三十三条规定，加害人实施家庭暴力，构成违反治安管理行为的，依法给予治安管理处罚；构成犯罪的，依法追究刑事责任。'), Document(id='5723459d-6178-4ae0-8ef3-3942695f9f4a', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第二十条规定，人民法院审理涉及家庭暴力的案件，可以根据公安机关出警记录、告诫书、伤情鉴定意见等证据，认定家庭暴力事实。'), Document(id='9e99f01f-c911-447b-9779-81ba185d9548', metadata={'source': {'source': 'G:\\GitHub\\Stu_AI\\StuFastAPI\\create_data\\法律数据集.csv'}}, page_content='《中华人民共和国反家庭暴力法》第三条规定，家庭成员之间应当互相帮助，互相关爱，和睦相处，履行家庭义务。反家庭暴力是国家、社会和每个家庭的共同责任。国家禁止任何形式的家庭暴力。')]
    rrf(v_result,b_result)
